export enum HitType {
    KICK = 36,
    SNARE_HEAD = 38,
    SNARE_RIM = 40,
    SNARE_XSTICK = 37,
    TOM1 = 48,
    TOM1_RIM = 50,
    TOM2 = 45,
    TOM2_RIM = 47,
    TOM3 = 43,
    TOM3_RIM = 58,
    HH_OPEN_BOW  = 46,
    HH_OPEN_EDGE = 26,
    HH_CLOSED_BOW = 42,
    HH_CLOSED_EDGE = 22,
    HH_PEDAL = 44,
    CRASH1_BOW = 49,
    CRASH1_EDGE = 55,
    CRASH2_BOW = 57,
    CRASH2_EDGE = 52,
    RIDE_BOW = 51,
    RIDE_EDGE = 59,
    RIDE_BELL = 53,
    AUX_HEAD = 27,
    AUX_RIM = 28,
    UNKNOWN = 0
}

export const HitTypeString: {[key: number]: string} = {
    [HitType.KICK]: "Kick",
    [HitType.SNARE_HEAD]: "Snare Head",
    [HitType.SNARE_RIM]: "Snare Rim",
    [HitType.SNARE_XSTICK]: "Snare XStick",
    [HitType.TOM1]: "Tom 1",
    [HitType.TOM1_RIM]: "Tom 2 Rim",
    [HitType.TOM2]: "Tom 2",
    [HitType.TOM2_RIM]: "Tom 2 Rim",
    [HitType.TOM3]: "Tom 3",
    [HitType.TOM3_RIM]: "Tom 3 Rim",
    [HitType.HH_OPEN_BOW]: "Hihat Open Bow",
    [HitType.HH_OPEN_EDGE]: "Hihat Open Edge",
    [HitType.HH_CLOSED_BOW]: "Hihat Closed Bow",
    [HitType.HH_CLOSED_EDGE]: "Hihat Closed Edge",
    [HitType.HH_PEDAL]: "Hihat Pedal",
    [HitType.CRASH1_BOW]: "Crash 1 Bow",
    [HitType.CRASH1_EDGE]: "Crash 1 Edge",
    [HitType.CRASH2_BOW]: "Crash 2 Bow",
    [HitType.CRASH2_EDGE]: "Crash 2 Edge",
    [HitType.RIDE_BOW]: "Ride Bow",
    [HitType.RIDE_EDGE]: "Ride Edge",
    [HitType.RIDE_BELL]: "Ride Bell",
    [HitType.AUX_HEAD]: "Aux Head",
    [HitType.AUX_RIM]: "Aux Rim",
    [HitType.UNKNOWN]: "Unknown",
}